### ISSUE TITLE
5.0 sequence of issues

### ISSUE THREAD

**Issue by neelsmith** [neelsmith/tabulae#177]
- [x] change `LemmatizedForm`'s `apply`  function to return an `Option[LemmatizedForm]` #181 
- [x] change `FstReader` to work in terms of an `Option[LemmatizedForm]` #182 
- [x] complete all categories of  `LemmatizedForm` object #166 
- [x] implement `FormTrait` for all categories #145

**Comment by neelsmith** [comment]
Complete. Publishing 5.0.
