### ISSUE TITLE
accessible checklist

### ISSUE THREAD

**Issue by neelsmith** [neelsmith/tabulae#186]
Utilities to assess a single corpus dataset:

- [ ] URN manager capable of expanding abbreviated URNs, and of validating usage in a corpus dataset
- [ ] ensure that all IDs are unique
- [ ] ensure that all data values are valid
